### ISSUE TITLE
Double to int conversion

### ISSUE THREAD

**Issue by astoupine** [BPOpt/Optimo#2] opened 2015-02-05 02:53 UTC
Hi,

In the initial solution list node, when the inputs for the upper and lower limits come into it, they get automatically converted into integers. The inputs could have to be doubles in some cases.

**Comment by BPOpt** [comment] 2015-02-05 16:49
The issue is addressed in the updated version. The updated version of the package will be uploaded to Dynamo packages as version 0.1.2

**Closed by BPOpt** 2015-02-05 16:49 UTC
